name       : perl-devel-hide
version    : 0.0009
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/F/FE/FERREIRA/Devel-Hide-0.0009.tar.gz : 71dec40b9e53cd2dc98301ea4a64e1a95b71aa414f9b0d6d28c56c54f8fa16de
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Devel::Hide - Forces the unavailability of specified Perl modules (for testing)
description: |
    Simple tool for developers which allows to hide installed Perl modules.
builddeps  :
    - perl-test-pod
    - perl-test-pod-coverage
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
