name       : perl-devel-hide
version    : '0.0010'
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/F/FE/FERREIRA/Devel-Hide-0.0010.tar.gz : 756fefa60febf1d8dbc851426bfb084520db45f745d35c8e8623945d6dda5e82
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Devel::Hide - Forces the unavailability of specified Perl modules (for
    testing)
description: |
    Simple tool for developers which allows to hide installed Perl modules.
builddeps  :
    - perl-test-pod
    - perl-test-pod-coverage
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
