name       : perl-devel-hide
version    : '0.0015'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/D/DC/DCANTRELL/Devel-Hide-0.0015.tar.gz : fc8dbeb7f7d75a78ed496b1e0e05cfc99c68acab3a2e92cff155ca5f0fa5df58
homepage   : https://metacpan.org/pod/Devel::Hide
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Devel::Hide - Forces the unavailability of specified Perl modules (for testing)
description: |
    Simple tool for developers which allows to hide installed Perl modules.
builddeps  :
    - perl-test-pod
    - perl-test-pod-coverage
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
